// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q      = new(Query)
	Grant  *grant
	Key    *key
	Server *server
	Token  *token
	User   *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Grant = &Q.Grant
	Key = &Q.Key
	Server = &Q.Server
	Token = &Q.Token
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:     db,
		Grant:  newGrant(db, opts...),
		Key:    newKey(db, opts...),
		Server: newServer(db, opts...),
		Token:  newToken(db, opts...),
		User:   newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Grant  grant
	Key    key
	Server server
	Token  token
	User   user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Grant:  q.Grant.clone(db),
		Key:    q.Key.clone(db),
		Server: q.Server.clone(db),
		Token:  q.Token.clone(db),
		User:   q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Grant:  q.Grant.replaceDB(db),
		Key:    q.Key.replaceDB(db),
		Server: q.Server.replaceDB(db),
		Token:  q.Token.replaceDB(db),
		User:   q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Grant  *grantDo
	Key    *keyDo
	Server *serverDo
	Token  *tokenDo
	User   *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Grant:  q.Grant.WithContext(ctx),
		Key:    q.Key.WithContext(ctx),
		Server: q.Server.WithContext(ctx),
		Token:  q.Token.WithContext(ctx),
		User:   q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
