// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yankeguo/bunker/model"
)

func newHostKey(db *gorm.DB, opts ...gen.DOOption) hostKey {
	_hostKey := hostKey{}

	_hostKey.hostKeyDo.UseDB(db, opts...)
	_hostKey.hostKeyDo.UseModel(&model.HostKey{})

	tableName := _hostKey.hostKeyDo.TableName()
	_hostKey.ALL = field.NewAsterisk(tableName)
	_hostKey.ID = field.NewString(tableName, "id")
	_hostKey.ServerID = field.NewString(tableName, "server_id")
	_hostKey.KeyType = field.NewString(tableName, "key_type")
	_hostKey.Fingerprint = field.NewString(tableName, "fingerprint")
	_hostKey.PublicKey = field.NewString(tableName, "public_key")
	_hostKey.CreatedAt = field.NewTime(tableName, "created_at")

	_hostKey.fillFieldMap()

	return _hostKey
}

type hostKey struct {
	hostKeyDo

	ALL         field.Asterisk
	ID          field.String
	ServerID    field.String
	KeyType     field.String
	Fingerprint field.String
	PublicKey   field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (h hostKey) Table(newTableName string) *hostKey {
	h.hostKeyDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hostKey) As(alias string) *hostKey {
	h.hostKeyDo.DO = *(h.hostKeyDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hostKey) updateTableName(table string) *hostKey {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewString(table, "id")
	h.ServerID = field.NewString(table, "server_id")
	h.KeyType = field.NewString(table, "key_type")
	h.Fingerprint = field.NewString(table, "fingerprint")
	h.PublicKey = field.NewString(table, "public_key")
	h.CreatedAt = field.NewTime(table, "created_at")

	h.fillFieldMap()

	return h
}

func (h *hostKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hostKey) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 6)
	h.fieldMap["id"] = h.ID
	h.fieldMap["server_id"] = h.ServerID
	h.fieldMap["key_type"] = h.KeyType
	h.fieldMap["fingerprint"] = h.Fingerprint
	h.fieldMap["public_key"] = h.PublicKey
	h.fieldMap["created_at"] = h.CreatedAt
}

func (h hostKey) clone(db *gorm.DB) hostKey {
	h.hostKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hostKey) replaceDB(db *gorm.DB) hostKey {
	h.hostKeyDo.ReplaceDB(db)
	return h
}

type hostKeyDo struct{ gen.DO }

func (h hostKeyDo) Debug() *hostKeyDo {
	return h.withDO(h.DO.Debug())
}

func (h hostKeyDo) WithContext(ctx context.Context) *hostKeyDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hostKeyDo) ReadDB() *hostKeyDo {
	return h.Clauses(dbresolver.Read)
}

func (h hostKeyDo) WriteDB() *hostKeyDo {
	return h.Clauses(dbresolver.Write)
}

func (h hostKeyDo) Session(config *gorm.Session) *hostKeyDo {
	return h.withDO(h.DO.Session(config))
}

func (h hostKeyDo) Clauses(conds ...clause.Expression) *hostKeyDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hostKeyDo) Returning(value interface{}, columns ...string) *hostKeyDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hostKeyDo) Not(conds ...gen.Condition) *hostKeyDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hostKeyDo) Or(conds ...gen.Condition) *hostKeyDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hostKeyDo) Select(conds ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hostKeyDo) Where(conds ...gen.Condition) *hostKeyDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hostKeyDo) Order(conds ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hostKeyDo) Distinct(cols ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hostKeyDo) Omit(cols ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hostKeyDo) Join(table schema.Tabler, on ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hostKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hostKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hostKeyDo) Group(cols ...field.Expr) *hostKeyDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hostKeyDo) Having(conds ...gen.Condition) *hostKeyDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hostKeyDo) Limit(limit int) *hostKeyDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hostKeyDo) Offset(offset int) *hostKeyDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hostKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *hostKeyDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hostKeyDo) Unscoped() *hostKeyDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hostKeyDo) Create(values ...*model.HostKey) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hostKeyDo) CreateInBatches(values []*model.HostKey, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hostKeyDo) Save(values ...*model.HostKey) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hostKeyDo) First() (*model.HostKey, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostKey), nil
	}
}

func (h hostKeyDo) Take() (*model.HostKey, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostKey), nil
	}
}

func (h hostKeyDo) Last() (*model.HostKey, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostKey), nil
	}
}

func (h hostKeyDo) Find() ([]*model.HostKey, error) {
	result, err := h.DO.Find()
	return result.([]*model.HostKey), err
}

func (h hostKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HostKey, err error) {
	buf := make([]*model.HostKey, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hostKeyDo) FindInBatches(result *[]*model.HostKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hostKeyDo) Attrs(attrs ...field.AssignExpr) *hostKeyDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hostKeyDo) Assign(attrs ...field.AssignExpr) *hostKeyDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hostKeyDo) Joins(fields ...field.RelationField) *hostKeyDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hostKeyDo) Preload(fields ...field.RelationField) *hostKeyDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hostKeyDo) FirstOrInit() (*model.HostKey, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostKey), nil
	}
}

func (h hostKeyDo) FirstOrCreate() (*model.HostKey, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HostKey), nil
	}
}

func (h hostKeyDo) FindByPage(offset int, limit int) (result []*model.HostKey, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hostKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hostKeyDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hostKeyDo) Delete(models ...*model.HostKey) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hostKeyDo) withDO(do gen.Dao) *hostKeyDo {
	h.DO = *do.(*gen.DO)
	return h
}
